name: Publish to registry

on:
  pull_request:
    types:
      - closed
    branches:
      - master
    paths-ignore:
      - '.github/**'

jobs:
  publish:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/reusable-publish.yml
    permissions: write-all
    with:
      appId: ${{ vars.ATLANTIS_SUPER_BOT_APP_ID }}
    secrets:
      appPrivateKey: ${{ secrets.ATLANTIS_SUPER_BOT_PRIVATE_KEY }}
      npmAuthToken: ${{ secrets.NPM_TOKEN }}
